import { type Express } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import accountsRouter from "./accounts";
import contactsRouter from "./contacts";
import settingsRouter from "./settings";
import dashboardRouter from "./dashboard";
import analysesRouter from "./analyses";
import insightsRouter from "./insights";
import sequencesRouter from "./sequences";
import activitiesRouter from "./activities";
import opportunitiesRouter from "./opportunities";
import experimentsRouter from "./experiments";
import analyzeRouter from "./analyze";
import issuesRouter from "./issues";
import generateMessageRouter from "./generate-message";
import repliesRouter from "./replies";
import tasksRouter from "./tasks";
import playbookRouter from "./playbook";

export function registerRoutes(app: Express) {
  app.use("/api", healthRouter);
  app.use("/api", authRouter);
  app.use("/api", accountsRouter);
  app.use("/api", contactsRouter);
  app.use("/api", settingsRouter);
  app.use("/api", dashboardRouter);
  app.use("/api", analysesRouter);
  app.use("/api", insightsRouter);
  app.use("/api", sequencesRouter);
  app.use("/api", activitiesRouter);
  app.use("/api", opportunitiesRouter);
  app.use("/api", experimentsRouter);
  app.use("/api", analyzeRouter);
  app.use("/api", issuesRouter);
  app.use("/api", generateMessageRouter);
  app.use("/api", repliesRouter);
  app.use("/api", tasksRouter);
  app.use("/api", playbookRouter);
}
